[package]
name = "filter"
version = "0.1.0"
edition = "2018"

[lib]
name = "filter"
path = "filter.rs"

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"

[features]
fma = []

